### ISSUE TITLE
Mixed debugging doesn't work with C++/CLI

### ISSUE THREAD

**Issue by adammarks** [adammarks/netcoreproto#3]
I normally setup mixed debugging so I can debug both native and managed code 
![Snag_1d19fd34](https://user-images.githubusercontent.com/1170063/70717927-547b8800-1cbd-11ea-83e8-2527dc8e1bae.png)

But when I do this I get this error when I hit my C++/CLI code ( when I do a Help->About in the app ) 
![Snag_1d1b605e](https://user-images.githubusercontent.com/1170063/70718079-8b519e00-1cbd-11ea-9cc8-1b6b3457e745.png)

I think this makes sense because "Mixed" debugging would normally probably mean Native + Managed .Net Framework.

I don't see an option for Native + Managed .Net Core though

**Comment by mjrousos** [comment]
Thanks for flagging this, @adammarks. I've run into it, as well. 

@nguerrera, do you know what the expectation is for mixed-mode native/.NET Core debugging? As Adam points out, it doesn't seem to work well at the moment. Is there a place in a Microsoft repo we should be tracking this issue?

**Comment by nguerrera** [comment]
Hmm, thanks for reporting, there is an option for mixed native + core when you do devenv /debugexe (which I use a bunch to debug mixed) and I think on attach as well. This might be an issue with the property pages.

**Comment by nguerrera** [comment]
@olgaark Is there something missing to have the option for mixed (native + core) shown in the property pages? Is there a manual equivalent that can be done in the vcxproj in the meantime?

**Comment by mjrousos** [comment]
According to @olgaark, this will be fixed in 16.5 preview 2 (though there's a known issue with hitting native breakpoints before managed code runs).

**Comment by adammarks** [comment]
This is fixed now,  there is a Mixed ( .NET Core ) option now:
![Snag_fb67bdc](https://user-images.githubusercontent.com/1170063/73679413-555ee380-4688-11ea-93bd-edbad907e31f.png)
